version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login  --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - ls -la
      - echo Building the Docker image...
      - docker build -f contrib/docker/Dockerfile -t superset:superset .
      - docker tag superset:superset $BUILD_REPOSITORY_URL/$BUILD_REPOSITORY_NAME:latest
      - docker ps
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $BUILD_REPOSITORY_URL/$BUILD_REPOSITORY_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name":"treasuryreport","imageUri":"%s"}]' $BUILD_REPOSITORY_URL/$BUILD_REPOSITORY_NAME:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
