version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login  --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - ls -la
      - echo fixing symbolic link...
      - rm superset/static/assets
      - ln -s ../assets/ superset/static/assets
      - echo Building the Docker image...
      - docker build -f contrib/docker/Dockerfile -t $BUILD_REPOSITORY_NAME .
      - docker tag $BUILD_REPOSITORY_NAME $BUILD_REPOSITORY_URL/$BUILD_REPOSITORY_NAME:$BUILD_IMAGE_TAG
      - docker image ls
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $BUILD_REPOSITORY_URL/$BUILD_REPOSITORY_NAME:$BUILD_IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"treasuryreport","imageUri":"%s"}]' $BUILD_REPOSITORY_URL/$BUILD_REPOSITORY_NAME:$BUILD_IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
